name: Taxonomy And Examples
on: [push, pull_request]

jobs:
  taxonomy_and_examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-taxonomypip
        restore-keys: |
          ${{ runner.os }}-taxonomypip
    - run: pip install --upgrade -r requirements.in
    # Check Taxanomy meets Taxonomy Schema
    - name: Check Taxanomy meets Taxonomy Schema
      run: jsonschema -i taxonomy/taxonomy.json taxonomy/schema/taxonomyschema.json
    # Check all examples match compiled schema
    #    - name: Compile
    #      run:  "python compile.py"
    #    - name: Check all examples match compiled schema
    #      run: "for f in examples/*; do   echo \"File: $f\"; jsonschema -i $f _compiled/360-giving-schema-including-extension.json || exit 1;   done"
    #
