name: Taxonomy And Examples
on: [push, pull_request]

jobs:
  taxonomy_and_examples:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
        architecture: x64
    - uses: actions/cache@v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-taxonomypip
        restore-keys: |
          ${{ runner.os }}-taxonomypip
    - run: pip install --upgrade jsonschema compiletojsonschema
    # Check Taxanomy meets Taxonomy Schema
    - name: Check Taxanomy meets Taxonomy Schema
      run: jsonschema -i taxonomy/taxonomy.json taxonomy/schema/taxonomyschema.json
    # Check all examples match compiled schema
    - name: Compile the extension schema
      run:  "compiletojsonschema --codelist-base-directory codelists/ --set-additional-properties-false-everywhere  schema/360-giving-schema-extension.json > _compiled/360-giving-schema-only-extension.json"
    - name: Check all examples match compiled schema
      run: "for f in examples/*; do   echo \"File: $f\"; jsonschema -i $f _compiled/360-giving-schema-only-extension.json || exit 1;   done"

